### ISSUE TITLE
Peer Review Checklist

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guides-template#12]
Peer Review

- [ ] Working instruction and sample code
- [ ] Quality of code (best coding practices)
- [ ] Quality and presentation of guide according to Structure and Style Guideline
- [ ] Consistency of guide with template and other guides
- [ ] Examples with the right outcomes are provided
- [ ] Example with the wrong outcomes, if any, are provided
- [ ] Check that all licensing statements are properly stated in all files
- [ ] Check that the pom.xml, server.xml, etc files are clean up
- [ ] Check that the directories are properly structured
- [ ] Test the guide on 3 platforms: Mac, Win, Liniux
- [ ] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [ ] If any URL visits, try curl command where applicable 
- [ ] Ensure that the automation tests are able to run with continuous daily build
- [ ] Ensure that the guide is using the latest version of the liberty-maven-plugin or gradle plugin
- [ ] Check that only these `page-tags` can be used in a guide (nothing else): `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE`
