### ISSUE TITLE
Pre-Publishing Tests Checklist

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guides-template#16]
Pre-Publishing Tests

- [ ] Check appearance (contents, headings, paragraphs, code snippets, outputs, links) of the guide on test site, ie, qa-guides
- [ ] Read through the guide 
- [ ] Clone repo and test finish directory with no error
- [ ] Run `diff -r start/ finish/` 
- [ ] Follow the instruction in the guide to test that it is working
- [ ] Check that the release date on the readme.adoc is the publishing date
