### ISSUE TITLE
Post-Publishing Tests Checklist

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guides-template#17]
Post-Publishing Tests

- [ ] Check appearance (contents, headings, paragraphs, code snippets, outputs, links) of the guide on openliberty.io
- [ ] Clone repo and test finish directory with no error
- [ ] Add description for the repo with link to guide's published website
- [ ] Enable pull creation notification on the repo for `was-lib-guides-alerts`, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Setup-Automation-Tests-For-OpenLiberty-Guides)

Other post-publishing tasks

- [ ] Ensure automated test using Travis, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Setup-Automation-Tests-For-OpenLiberty-Guides) 
- [ ] Add the new guide's repo to the `OpenLiberty/guides-common` ZenHub board
- [ ] Send announcement to slack channels
- [ ] Consider SEO title and description for the guides
- [ ] Enable `master` branch lock down
