### ISSUE TITLE
PR readiness checklist

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guides-template#40]
```
Readiness checklist:
- [ ] verify on the guides development site VM
- [ ] verify end-to-end locally if the source has change
- [ ] verify end-to-end on cloud-hosted if apply
- [ ] PR test pass
```
