### ISSUE TITLE
Todo app feedback

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guides-template#6]
- [x] /finish/src/main/java/io/openliberty/guides/todo/ => Perhaps rename "todo" to "todolistSample"? 

- [x] /finish/src/main/java/io/openliberty/guides/todo/ => the different folders for models, resources look good. Are services the same as resources? Or the TodoService need to be renamed. Work with @JunyiSun on this. Same with SampleTodoService class. 

- [x] The path name "todos" in "@Path("todos")" in TodoResource class can be improved

- [x] The "Main.java" class name can be "TodoApplication"?

**Comment by proubatsis** [comment]
@evelinec services are not quite the same as resources. They can be thought of as what InventoryManager is to InventoryResource. It may need to be changed to follow whatever naming conventions need to be followed by our team. cc @JunyiSun

**Comment by evelinec** [comment]
Yes @proubatsis, some renaming is neccessary. Take a look at the code in existing guides and consult @JunyiSun where needed. Thanks.

**Comment by proubatsis** [comment]
@JunyiSun @evelinec 

> /finish/src/main/java/io/openliberty/guides/todo/ => the different folders for models, resources look good. Are services the same as resources? Or the TodoService need to be renamed. Work with @JunyiSun on this. Same with SampleTodoService class.

I can change `TodoService` to `TodoManager`, and `SampleTodoService` to `SampleTodoManager`. Does that work?

> The path name "todos" in "@path("todos")" in TodoResource class can be improved

It's unclear what I should do here. It would probably be best to drop the `s` and just make the path `todo`, is this good or were you thinking of something else?

The other two points are clear enough as to the required change.

**Comment by JunyiSun** [comment]
@proubatsis I am okay with renaming them. Please also update the README.adoc (there are several mentions there)  when you make the changes.  Thank you.

**Comment by proubatsis** [comment]
Fixed in #7

**Comment by evelinec** [comment]
Looks good. Can close.
